---
- name: Simulate a failing job with a traceback
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Execute a Python script that intentionally raises an exception
      ansible.builtin.script: |
        #!/usr/bin/env python3
        import sys
        
        def main():
            raise ValueError("Receptor detail:\nFinished")

        if __name__ == "__main__":
            try:
                main()
            except Exception as e:
                raise e
      args:
        executable: python3
      register: script_output
      ignore_errors: no

