---
- name: Stress Test Limits with stress-ng
  hosts: all
  vars:
    stress_cpu: false
    stress_memory: true
    cpu_cores: 8
    memory_workers: 4
    memory_bytes: "4g"
    time_out: 300

  tasks:
    #- name: Install stress-ng
    #  ansible.builtin.package:
    #    name: stress-ng
    #    state: present
    #  become: yes

    - name: Stress CPU
      ansible.builtin.command: stress-ng --cpu {{ cpu_cores }} --timeout {{ time_out }} --metrics-brief
      async: "{{ time_out }}"
      poll: 0
      register: cpu_stress
      when: stress_cpu

    - name: Stress Memory
      ansible.builtin.command: stress-ng --vm {{ memory_workers }} --vm-bytes {{ memory_bytes }} --timeout {{ time_out }} --vm-hang 1 --metrics-brief
      async: "{{ time_out }}"
      poll: 0
      register: memory_stress
      when: stress_memory

    - name: Wait for CPU stress to complete
      ansible.builtin.async_status:
        jid: "{{ cpu_stress.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 60
      when: stress_cpu

    - name: Wait for Memory stress to complete
      ansible.builtin.async_status:
        jid: "{{ memory_stress.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 10
      delay: 60
      when: stress_memory
